baseURL = "/"
languageCode = "en-us"
title = "sakshi"
theme = [ "PaperMod" ]

[params]
hideFooter = true

  [params.profileMode]
  enabled = true
  title = "Hi there 👋, I am Sakshi"
  subtitle = """
### 4th year CSE student @ PESU ECC | Full-stack Developer.
---
 I am always.
 """
  imageTitle = "My image "
  imageWidth = 120
  imageHeight = 120

    [[params.profileMode.buttons]]
    name = "About"
    url = "/about"

    [[params.profileMode.buttons]]
    name = "Techstack"
    url = "/techstack"

    [[params.profileMode.buttons]]
    name = "Projects"
    url = "/projects"

    [[params.profileMode.buttons]]
    name = "View Resume"
    url = ""

  [[params.socialIcons]]
  name = "LinkedIn"
  url = ""

  [[params.socialIcons]]
  name = "Github"
  url = "https://github.com/sakshi666"

  [[params.socialIcons]]
  name = "Gmail"
  url = "mailto:sakshi4681@gmail.com"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "techstack"
name = "Techstack"
url = "/techstack/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 10

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 30

