baseURL = "/"
languageCode = "en-us"
title = "samridh3215"
theme = [ "PaperMod" ]

[params]
hideFooter = true

  [params.profileMode]
  enabled = true
  title = "Hi there 👋, I am Samridh Anand"
  subtitle = """
### 4th year CSE student @ PESU ECC | Cybersecurity Enthusiast | Full-stack Developer.
---
 I am always actively looking out for opportunities to learn and improve my skillset. Through out my academic journey, I have explored a lot of fields in computer science, for example, computer vision, web development, native android development, machine learning and AI, and even cybersecurity.
 """
  imageTitle = "My image "
  imageWidth = 120
  imageHeight = 120

    [[params.profileMode.buttons]]
    name = "About"
    url = "/about"

    [[params.profileMode.buttons]]
    name = "Techstack"
    url = "/techstack"

    [[params.profileMode.buttons]]
    name = "Projects"
    url = "/projects"

    [[params.profileMode.buttons]]
    name = "View Resume"
    url = "https://rxresu.me/samridh3215/samridh-resume"

  [[params.socialIcons]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/samridh-anand-985415241/"

  [[params.socialIcons]]
  name = "Github"
  url = "https://github.com/samridh3215"

  [[params.socialIcons]]
  name = "Gmail"
  url = "mailto:samridhanand.2003@gmail.com"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "techstack"
name = "Techstack"
url = "/techstack/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 10

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 30

